name: deploy

on:
  push:
    branches: [ SP-5879_increment_version_number ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/set-metaapp-home-path.sh
      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh
      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
      - name: Archiving project
        run: .github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: .github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: .github/scripts/publish_testflight.sh
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD
