name: JIRA
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Issue
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: SP
          issuetype: Bug
          summary: "[SDK] ${{ github.event.issue.title }}"
          description: ${{ github.event.issue.body }}
