name: Swift
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing SwiftLint
        run: brew install swiftlint
      - name: linting
        run: cd Example && swiftlint lint
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: CocoaPod Install
        run: cd Example && pod install
      - name: iOS build
        run: xcodebuild build-for-testing -scheme ConsentViewController_ExampleTests -workspace Example/ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
      - name: testing -> iPhone 11 (iOS 13.5)
        run: xcodebuild test-without-building -scheme ConsentViewController_ExampleTests -workspace Example/ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
