name: Test
on:
  workflow_dispatch:
  push:
    branches: [ develop, legacy/v6 ]
  pull_request:
    branches: [ develop, legacy/v6 ]
defaults:
  run:
    working-directory: Example
jobs:
  lint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: linting
        run: swiftlint lint
  BuildSwiftPackage:
      runs-on: macos-12
      steps:
        - uses: actions/checkout@v2
        - name: Select Xcode version 14.0.1
          run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
        - name: Building Swift Package
          run: xcodebuild clean build -scheme SPMBuild -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
        - uses: actions/upload-artifact@v2
          if: failure()
          name: Upload Swift Package build results
          with:
            path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult
  ObjC-ExampleApp-tests:
      runs-on: macos-12
      steps:
        - uses: actions/checkout@v2
        - name: Select Xcode version 14.0.1
          run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
        - name: ObjC-ExampleApp testing -> iPhone 14 Pro (iOS 16.0)
          run: xcodebuild test -scheme ObjC-ExampleApp -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
        - uses: actions/upload-artifact@v2
          if: failure()
          name: Upload ObjCExampleApp tests results
          with:
            path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult
  # NativeMessageExample-tests:
  #     runs-on: macos-12
  #     steps:
  #       - uses: actions/checkout@v2
  #       - name: Select Xcode version 14.0.1
  #         run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
  #       - name: NativeMessageExample testing -> iPhone 14 Pro (iOS 16.0)
  #         run: xcodebuild test -scheme NativeMessageExample -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
  #       - uses: actions/upload-artifact@v2
  #         if: failure()
  #         name: Upload NativeMessageExample tests results
  #         with:
  #           path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult
  ConsentViewController:
      runs-on: macos-12
      steps:
        - uses: actions/checkout@v2
        - name: Select Xcode version 14.0.1
          run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
        - name: ConsentViewController testing -> iPhone 14 Pro (iOS 16.0)
          run: xcodebuild test -scheme ConsentViewController_Example -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
        - uses: actions/upload-artifact@v2
          if: failure()
          name: Upload ConsentViewController tests results
          with:
            path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult
  AuthExample-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version 14.0.1
        run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
      - name: ConsentViewController testing -> iPhone 14 Pro (iOS 16.0)
        run: xcodebuild test -scheme AuthExample -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
      - uses: actions/upload-artifact@v2
        if: failure()
        name: Upload ConsentViewController tests results
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult
  # NativePMExampleApp:
  #     runs-on: macos-12
  #     steps:
  #       - uses: actions/checkout@v2
  #       - name: Select Xcode version 14.0.1
  #         run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
  #       - name: ConsentViewController testing -> iPhone 14 Pro (iOS 16.0)
  #         run: xcodebuild test -scheme NativePMExampleApp -workspace ConsentViewController.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV,OS=16.1'
  #       - uses: actions/upload-artifact@v2
  #         if: failure()
  #         name: Upload NativePMExampleApp tests results
  #         with:
  #           path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult 
  # MetaApp:
  #     runs-on: macos-12
  #     steps:
  #       - uses: actions/checkout@v2
  #       - name: Select Xcode version 14.0.1
  #         run: sudo xcode-select -s '/Applications/Xcode_14.0.1.app/Contents/Developer'
  #       - name: SourcePointMetaApp testing -> iPhone 14 Pro (iOS 16.0)
  #         run: xcodebuild test -scheme SourcePointMetaApp -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
  #       - uses: actions/upload-artifact@v2
  #         if: failure()
  #         name: Upload SourcePointMetaApp tests results
  #         with:
  #           path: /Users/runner/Library/Developer/Xcode/DerivedData/**/*.xcresult         
